### ISSUE TITLE
dmd version not compatible with macOS Catalina

### ISSUE THREAD

**Issue by philwo** [bazelbuild/rules_d#37]
The versions of dmd here: https://github.com/bazelbuild/rules_d/blob/master/d/d.bzl#L571 are not compatible with macOS Catalina: https://issues.dlang.org/show_bug.cgi?id=20019 and have to be updated.

This is currently causing the CI to be red for rules_d: https://github.com/bazelbuild/continuous-integration/issues/930

**Comment by laurentlb** [comment]
Should be fixed with https://github.com/bazelbuild/rules_d/pull/38 (thanks to @meteorcloudy)
